- kubernetes/machine-class.yaml
- pkg/driver/driver.go
- pkg/driver/utils.go
Check to validate if the MachineClass in the scope is the MachineClass for the corresponding cloud provider
Fixes [#599](https://github.com/gardener/machine-controller-manager/issues/599)
```improvement user
NONE
```
> Add checks to verify the support for incoming machine class

- pkg/client/factory.go
This PR fixes an issue which discarded the region configuration for the Neutron client.
/invite @kon-angelo 
/cc @vasu1124 
```improvement operator
An issue has been fixed which prevented ports from being patched properly after machine creations.
```
> Fix used region for Neutron client

- Dockerfile
- pkg/apis/cloudprovider/cloudprovider.go
- pkg/apis/validation/validation.go
- pkg/apis/validation/validation_test.go
- pkg/client/credentials.go
- pkg/client/factory.go
The secret backing the machine class object can contain the keys `applicationCredentialID` and `applicationCredentialSecret` as alternative to authentication with username/password.
Fixes #
```improvement user
add support for authentication with application credentials
```
> add support for authentication with application credentials

- pkg/apis/cloudprovider/cloudprovider.go
- pkg/apis/validation/validation.go
- pkg/apis/validation/validation_test.go
- pkg/client/credentials.go
- pkg/client/factory.go
Also support authentication with application credentials using (`username`,`applicationCredentialName`,  `applicationCredentialSecret`) instead of (`applicationCredentialID`, `applicationCredentialSecret`)
Fixes #
```improvement user
```
> support for applicationCredentialName

- pkg/driver/executor/executor.go
- pkg/driver/executor/executor_test.go
This PR introduces improvements for when the machineClass specifies a subnet. It introduces an additional GET check to see if the port that has to be created is already there from a previous attempt and if so it reuses that port.
In addition:
+ it refactors `resolveServerNetworks` into 2 different ones. The first calculates the network arguments for the server creation and the second calculates the server ports that must be patched to accept pod network traffic.
+  Fixes #23 by making the patching of server's ports happen on `GetMachineStatus` too.  This is a similar approach to the one done in https://github.com/gardener/machine-controller-manager-provider-aws/pull/39.
Fixes #23 
**Special notes for your …
> Improvements for User-managed network

- pkg/client/errors.go
- pkg/driver/driver.go
- pkg/driver/executor/executor.go
- pkg/driver/executor/executor_test.go
- pkg/driver/executor/utils.go
This PR fixes the following issues:
+ Fixes a bug where gardener managed server ports would orphan after a user manually deletes a server directly via the openstack CLI
+ Fixes a bug where the port of a server would orphan after a failed delete attempt
+ Minor refactoring
Fixes #
To fix the issue with the orphan ports during creation the getMachineStatus has been changed to return as unimplemented. This will make the machine controller to always call createMachine in order to create or adopt a machine. Since createMachine is idempotent there should not be issues. 
```improvement user
Fix a bug where orphan ports would be left during a failed create attempt.
Fix …
```
> Fix for orphan ports on {create,delete} machine

- pkg/driver/executor/executor.go
/kind bug
/kind regression
Fixes #48
```bugfix user
A regression in Machine creation from imageName is now fixed.
```
> Fix machine creation from imageName

- pkg/driver/executor/executor.go
/kind/bug
/kind/regression
Cherry pick of #49 on rel-v0.8.
#49: Fix machine creation from imageName
**Release Notes:**
```bugfix user
A regression in Machine creation from imageName is now fixed.
```
> [rel-v0.8] Automated cherry pick of #49: Fix machine creation from imageName

- cmd/machine-controller/main.go
- go.mod
- pkg/client/factory.go
- pkg/driver/driver.go
- pkg/driver/executor/executor.go
/area/dev-productivity
/area/ops-productivity
/kind/bug
Cherry pick of #47 on rel-v0.8.
#47: Use proper version of klog
**Release Notes:**
```bugfix operator
An issue causing klog's `--v` flag to be not respected is now fixed.
```
> [rel-v0.8] Automated cherry pick of #47: Use proper version of klog

- pkg/driver/executor/executor.go
Adds the missing pending state downloading.
Fixes #60 
```bugfix operator
Fixed missing volume status VolumeStatusDownloading when creating volume
```
> Fixed missing volume status downloading

- Dockerfile
Fixes #
```improvement user
Use distroless base image
```
> Change base image to distroless

- Makefile
- test/integration/provider/openstack.go
- test/integration/provider/rti.go
Similar to https://github.com/gardener/machine-controller-manager-provider-aws/pull/85
Fixes #
```improvement developer
probeResources() now doesn't try to delete orphan resources but only lists them.
The beforeSuite for IT test now calls for cleanup of orphan resources separately.
The Integration Test, which looks for orphan resources, now doesn't try to delete the orphan resources and just waits for them to be done automatically.
```
> rework orphan deletion

- .ci/set_dependency_version
Run `make revendor` because the revendor command also makes vendored gardener scripts executable.
Fixes #
```improvement user
Fix an issue where automatic revendoring did not assign correct permissions to CI scripts.
```
> fix issue with g/g scripts not having correct permissions

- pkg/driver/executor/executor.go
- pkg/driver/executor/executor_test.go
Fixes https://github.com/gardener/machine-controller-manager-provider-openstack/issues/54
Delete all ports matching machine name.
```bug user
Delete all ports matching machine name.
```
> fix multiple ports during delete

- .ci/pipeline_definitions
Add cve categorization for mcm-provider-openstack.
The categorization was initially defined here and it transferred as defined to the mcm-provider-openstack repository: 
https://github.com/gardener/gardener-extension-provider-openstack/pull/553 
We move the cve categorization to the mcm-provider-openstack repository as the categorization can't be taken into consideration when it is defined in the respective provider extension project. Once this behaviour has changed we can remove the categorisation here again.
```other operator
CVE categorization for mcm-provider-openstack has been added.
```
> Add cve categorization for mcm-provider-openstack

- .gitignore
- Makefile
This PR updates Makefile content to import dynamic content from the .env file.
Fixes -> https://github.com/gardener/machine-controller-manager/issues/846 
```improvement user
NONE
```
> Moved Declaration of dynamic content from Makefile to .env file for OPENSTACK

- .ci/pipeline_definitions
**What this PR does / why we need it**
Fix an oversight from https://github.com/gardener/machine-controller-manager-provider-openstack/pull/105: update-component-deps needs to "see" release-versions (from `releases` ocm repository).
This change will have no visible impact for users of this component (therefore I did not add a release-note).
> fix: configure update-dependencies-job to look for releases

- Makefile
Reverts gardener/machine-controller-manager-provider-openstack#109.
> Revert " Fixed the makefile"

- pkg/driver/executor/executor.go
In case of a `RootDiskType` is specified the volume will be created before creating the server. Also while deletion the server gets deleted first and than also the volume is getting deleted.
In the `BlockDeviceMapping` currently we set `DeleteOnTermination: true` this is wrong because the volume gets deleted by the mcm.
```bugfix operator
Set DeleteOnTermination for in BlockDeviceMappings to false in case of volumes with RootDiskType.
```
> Set DeleteOnTermination for in BlockDeviceMappings to false in case of volumes with RootDiskType

- pkg/driver/executor/executor.go
This PR increase the openstack poll interval from 1 second to 10 seconds. In my opinion there is no need to poll every second. All this tasks need a few second and to reduce the number of API calls against openstack is suggest to set the interval to 10 seconds.
Additionally I switched from the depricated `wait.Poll` to `wait.PollUntilContextTimeout`
Fixes #
```improvement operator
Increase openstack poll interval to reduce the number of openstack API calls.
```
> Increase openstack poll interval

- .ci/local_integration_test
- Makefile
This PR modifies the IT test make target to incorporate shoot as a seed setup as well as seed setup for local IT.
Fixes #
```other operator
NONE
```
> Enhanced the local_integration_test script

- .ci/set_dependency_version
/area dev-productivity
/kind impediment
/platform aws
Replace `make revendor` with `make tidy` in `set_dependency_version` script.
Fixes #
```other operator
NONE
```
> Fix set_dependency_version script

- Makefile
This PR provides a flag to specify target platform for the docker image
/area dev-productivity
Fixes #https://github.com/gardener/machine-controller-manager/issues/921
```other operator
```
> fixes docker image

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/flaking-test.md
- .github/pull_request_template.md
- hack/update-github-templates.sh
/area documentation
/kind bug
The /platform field in the repository templates for issues and PRs was wrongly set to aws and should be switched to openstack.
Fixes #
```other developer
Set repository PR template /platform from aws to openstack
```
> Fix templates

- Makefile
- hack/api-reference/api.md
- pkg/apis/openstack/types.go
- pkg/apis/openstack/v1alpha1/types.go
- pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
- pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/openstack/zz_generated.deepcopy.go
- pkg/apis/validation/validation.go
- pkg/apis/validation/validation_test.go
- pkg/driver/executor/executor.go
/area conrol-plane
/kind bug
Necessary to create machines after https://github.com/gardener/gardener-extension-provider-openstack/pull/850
Fixes #
```other operator
Allow input of pod CIDRs as slice.
```
> fix issue with gg 1.103 with pod network being a slice

- pkg/driver/executor/executor.go
/area control-plane
/kind regression
Increase timeout of server status checks 
Fixes #
```other operator
Increase VM status check timeout to 1200 seconds.
```
> increase server status timeouts
